[package]
name = "openhmd-rs-sys"
version = "0.1.3"
description="Unsafe OpenHMD bindings"
license="MIT"
authors = ["TheHellBox <thehellbox11@gmail.com>"]
repository = "https://github.com/TheHellBox/openhmd-rs-sys"
[dependencies]
libc = "0.2.35"
